var guestList = ["Arfat", "kamran", "Asif"];
var dontCome = guestList[1];
console.log(dontCome, "nai aha sakta");
guestList.splice(0, 1, "hussain");
console.log("Good news ! we found a big table for dinner");
guestList.unshift("Atif");
guestList.push("sufiyan");
var middleIndex = Math.floor(guestList.length / 2);
guestList.splice(middleIndex, 0, "Ahmed");
console.log("updated list for guest");
guestList.forEach(function (guestList) { return console.log("salam ".concat(guestList, " , would you like to dinner with me?")); });
